### PR TITLE
Adding logrotate file for horizon logfiles.

### PR DESCRIPTION
**Pull request by mnederlof**

### CODE REVIEW

**Comment by fpytloun** [comment]
Logrotate file should be shipped together with package. Why it's not?

**Comment by mnederlof** [comment]
Well, actually, it is configured here: https://github.com/salt-formulas/salt-formula-horizon/blob/master/horizon/files/horizon_settings/_horizon_settings.py#L58

So maybe that is the reason it was not in the package? (since the /var/log/horizon directory is also created / persisted by salt)

**Comment by fpytloun** [comment]
I see.. actually I am thinking about making integration with salt-formula-logrotate using meta support instead than managing logrotate files this way. Give me some time to think about it.. :-)

**Comment by mnederlof** [comment]
Will do :-)

**Comment by fpytloun** [comment]
https://github.com/salt-formulas/salt-formula-logrotate/pull/5
https://github.com/salt-formulas/salt-formula-horizon/pull/21

Untested.. yet :-)

**Comment by fpytloun** [comment]
Cleaning up this one, correct fixes will be merged during today.

**Pull request closed without merging**
